// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || (typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_URL) || "https://uvpxfbucgcpsjwahmvjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || (typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY) || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2cHhmYnVjZ2Nwc2p3YWhtdmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyODc4MzIsImV4cCI6MjA4Mzg2MzgzMn0.cyfjlAm-k3g4vDF814UGYdnb9vhvBfkcMFhFpwSGRIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});